language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
services:
- postgresql
- mysql
env:
- DONOTGOONWEB=True
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- pip install pipenv
- pipenv install --dev
- pipenv shell

script:
- python setup.py test
- coverage run --source=piecash setup.py test
after_success: coveralls
sudo: false
deploy:
  provider: pypi
  user: sdementen
  password:
    secure: JDJrFwdiEbyY6T3GE+XJv6lX/EpyjMeADGRKXZKalKebbGXqxG1198DaC0zKi2CwWQ57qv1z2JvCr2xDkw5zn5o/0DFdONnQegz+PtNUP+LvRCqoxo8wYGwYmKGmBSCfXI9j0jsfuE3xqx7KRwHMNGlrfBVETo6fTsngaEqPY3g=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: sdementen/piecash
    all_branches: master
    condition: $PYTHON_VERSION=3.5
