language: python

python:
- '2.7'
- '3.3'
- '3.4'

services:
- postgresql
- mysql

install:
 - pip install -r requirements-dev.txt
# - pip install coveralls

script:
 - python setup.py test
# - coverage run --source=piecash setup.py test

after_success:
  coveralls

sudo: false

deploy:
  provider: pypi
  user: sdementen
  password:
    secure: kIW3wjCwmXVO5XyCU9SjT4NZxAcq/9XBjHKN5HuD8ACZzlaqxU3UI8YKTE3O8XFNaT56/6bySLDrR83O4+s7bcIW/tWacky5PqKSkTuYhyQfnggHn4EQC5iDBSYYONPIBwIMb28pCLps3HMAT2F868iGHpFge7hr+YQBwZ5O1Io=
  on:
    repo: sdementen/piecash
    tags: true
    all_branches: master
    condition: $PYTHON_VERSION=3.4
